export const cuisines = [
  { id: 1, name: "Indian" },
  { id: 2, name: "Italian" },
  { id: 3, name: "Chinese" },
  { id: 4, name: "Mexican" },
  { id: 5, name: "Thai" },
  { id: 6, name: "Japanese" },
  { id: 7, name: "Turkish" },
  { id: 8, name: "American" },
  { id: 9, name: "French" },
  { id: 10, name: "Greek" },
  { id: 11, name: "Spanish" },
  { id: 12, name: "Moroccan" },
  { id: 13, name: "Vietnamese" },
  { id: 14, name: "British" },
  { id: 15, name: "Russian" },
  { id: 16, name: "Malaysian" },
  { id: 17, name: "Filipino" },
  { id: 18, name: "Polish" },
  { id: 19, name: "Ukrainian" },
];
export const letters =
[
  { "id": 1, "letter": "A" },
  { "id": 2, "letter": "B" },
  { "id": 3, "letter": "C" },
  { "id": 4, "letter": "D" },
  { "id": 5, "letter": "E" },
  { "id": 6, "letter": "F" },
  { "id": 7, "letter": "G" },
  { "id": 8, "letter": "H" },
  { "id": 9, "letter": "I" },
  { "id": 10, "letter": "J" },
  { "id": 11, "letter": "K" },
  { "id": 12, "letter": "L" },
  { "id": 13, "letter": "M" },
  { "id": 14, "letter": "N" },
  { "id": 15, "letter": "O" },
  { "id": 16, "letter": "P" },
  { "id": 17, "letter": "Q" },
  { "id": 18, "letter": "R" },
  { "id": 19, "letter": "S" },
  { "id": 20, "letter": "T" },
  { "id": 21, "letter": "U" },
  { "id": 22, "letter": "V" },
  { "id": 23, "letter": "W" },
  { "id": 24, "letter": "X" },
  { "id": 25, "letter": "Y" },
  { "id": 26, "letter": "Z" }
]

